#!/usr/bin/env bash

# Purpose:
#
# Runs a console command in the app container.

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

docker run --rm -it -v=$PWD:/app/ composer:latest composer $@
